
export default [
  {
    id: "1",
    title: "Redragon K512",
    brand: "Redragon",
    category: "keyboard",
    price: 20,
    images: [
      "https://m.media-amazon.com/images/I/71w9I5LAUZL.jpg",
      "https://m.media-amazon.com/images/I/71TCFwrskRL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71KGIiceY-L._AC_SX679_.jpg",
    ],
    description: "Redragon K512 RGB Keyboard Mechanical Feeling switches",
    count: 7,
    rating: 4,
    raters: 15,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "2",
    title: "Redragon H320",
    brand: "Redragon",
    category: "headphone",
    price: 32,
    images: [
      "https://m.media-amazon.com/images/I/61Oq9Iv8UhL.jpg",
      "https://m.media-amazon.com/images/I/51h+NmzYHLL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51XmajOZATL._AC_SX679_.jpg",
    ],
    description: "Redragon H320 Headset",
    count: 3,
    rating: 3,
    raters: 6,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "3",
    title: "Razer Basilisk X",
    brand: "Razer",
    category: "mouse",
    price: 38,
    images: [
      "https://m.media-amazon.com/images/I/81W3s4ZWMXL.jpg",
      "https://m.media-amazon.com/images/I/81iGgxdBcHL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71tmUKvm1eL._AC_SX679_.jpg",
    ],
    description:
      "Razer Basilisk X Hyperspeed Wireless Gaming Mouse: Bluetooth & Wireless Compatible",
    count: 2,
    rating: 5,
    raters: 2,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "4",
    title: "Apple MacBook Pro 2020",
    brand: "Apple",
    category: "laptop",
    price: 1500,
    images: [
      "https://m.media-amazon.com/images/I/31MQgbpmcSL._AC_SY780_.jpg",
      "https://m.media-amazon.com/images/I/81AkdxBCVpL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/91xkiFp-lzL._AC_SX679_.jpg",
    ],
    description:
      "Apple MacBook Pro 2020 Model (13-Inch, Apple M1 chip with 8-core CPU and 8-core GPU, 8GB, 512GB, Touch Bar and Touch ID, MYD92 ), Eng-KB, Space Gray",
    count: 6,
    rating: 4,
    raters: 35,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "5",
    title: "Lenovo Legion 5",
    brand: "Lenovo",
    category: "laptop",
    price: 1300,
    images: [
      "https://m.media-amazon.com/images/I/61gN58M6OXL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41k52BqPcFL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/413yODSEKsL._AC_.jpg",
    ],
    description:
      "Lenovo Legion 5 15ITH6 Gaming laptop - 11th Intel Core i5-11400H 6-Cores, 16GB RAM, 1TB SSD, NVIDIA GeForce RTX 3060 6GB GDDR6 Graphics, 15.6 FHD IPS 165Hz, 4-Zone RGB Backlit - Dos - Phantom Blue",
    count: 3,
    rating: 3,
    raters: 26,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "6",
    title: "HyperX Alloy",
    brand: "HyperX",
    category: "keyboard",
    price: 100,
    images: [
      "https://m.media-amazon.com/images/I/71HV-xAiyML._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/918ZagKPirL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81s09Lsv-mL._AC_SX679_.jpg",
    ],
    description: "HyperX Alloy OriginsTM 60 Mechanical Gaming Keyboard",
    count: 8,
    rating: 5,
    raters: 49,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "7",
    title: "Redragon K530 Draconic",
    brand: "Redragon",
    category: "keyboard",
    price: 60,
    images: [
      "https://m.media-amazon.com/images/I/61kEZ+2VX+L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71Ck5iSwVtL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71pvd5LWgwL._AC_SX679_.jpg",
    ],
    description:
      "Redragon K530 Draconic 60% Compact RGB Wireless Mechanical Keyboard, 61 Keys TKL Designed 5.0 Bluetooth Gaming Keyboard with Brown Switches and 16.8 Million RGB Lighting",
    count: 5,
    rating: 4,
    raters: 54,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "8",
    title: "HP 15-dw3033dx Laptop",
    brand: "HP",
    category: "laptop",
    price: 600,
    images: [
      "https://m.media-amazon.com/images/I/81qohiv33aL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81mlhJq4JbL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71yZp-Ru4WL._AC_SX679_.jpg",
    ],
    description:
      "HP 15-dw3033dx Laptop - 11th Intel core i3-1115G4, 8GB RAM, 256GB SSD, Intel UHD Graphics, 15.6 FHD (1920 x 1080) IPS micro-edge anti-glare 250 nits, FingerPrint, Windows 10, Natural Silver",
    count: 3,
    rating: 4,
    raters: 35,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "9",
    title: "HP Laptop 15-dw3014ne",
    brand: "HP",
    category: "laptop",
    price: 750,
    images: [
      "https://m.media-amazon.com/images/I/31KUAop6x6L._AC_.jpg",
      "https://m.media-amazon.com/images/I/311wmWAZq8L._AC_.jpg",
      "https://m.media-amazon.com/images/I/21gcxMSlrXL._AC_.jpg",
    ],
    description:
      "HP Laptop 15-dw3014ne - 11th Intel Core i5-1135G7, 8GB RAM, 256GB SSD, NVIDIA GeForce MX350 2GB GDDR5 dedicated Graphics, 15.6 FHD (1920 x 1080) micro-edge, anti-glare 250 nits, Dos - Natural silver",
    count: 8,
    rating: 5,
    raters: 62,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "10",
    title: "Lenovo V15 IML Laptop",
    brand: "Lenovo",
    category: "laptop",
    price: 550,
    images: [
      "https://m.media-amazon.com/images/I/51Ctf05l7EL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61iWNQ9SUzL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51zP3j99MbL._AC_SX679_.jpg",
    ],
    description:
      "Lenovo V15 IML Laptop - Intel Core i5-10210U, 8GB RAM, 1TB HDD, Intel UHD Graphics, 15.6 FHD (1920x1080) IPS 250nits Anti-glare, Dos - Iron",
    count: 9,
    rating: 4,
    raters: 23,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "11",
    title: "Lenovo IdeaPad Gaming",
    brand: "Lenovo",
    category: "laptop",
    price: 750,
    images: [
      "https://m.media-amazon.com/images/I/51PptKyIYbL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/5181KF5br-L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/417ch4TBOCL._AC_SX679_.jpg",
    ],
    description:
      "Lenovo IdeaPad Gaming 3 Laptop - Ryzen 5 5600H 6 Cores, 16GB RAM ,1TB HDD+ 256GB SSD, NVIDIA GeForce GTX 1650 4GB GDDR6 Graphics, 15.6 FHD (1920x1080) IPS 120Hz , Dos - Shadow Black",
    count: 13,
    rating: 2,
    raters: 12,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "12",
    title: "Apple MacBook Pro 2022",
    brand: "Apple",
    category: "laptop",
    price: 1650,
    images: [
      "https://m.media-amazon.com/images/I/61NRYreJ2cL._AC_SX679_.jpg",
      "https://tejarra-media.s3.amazonaws.com/98033/conversions/71CVoc1XVIL._AC_SL1500_-medium.jpg",
      "https://www.digitaltrends.com/wp-content/uploads/2020/12/macbook-pro-m1-08.jpg?p=1",
    ],
    description:
      "2022 Apple MacBook Pro laptop with M2 chip: 13-inch Retina display, 8GB RAM, 256GB SSD storage, Touch Bar, FaceTime HD camera. Works with iPhone and iPad; Space Grey",
    count: 8,
    rating: 5,
    raters: 32,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "13",
    title: "Apple Macbook Air 2020",
    brand: "Apple",
    category: "laptop",
    price: 1450,
    images: [
      "https://m.media-amazon.com/images/I/61sP4BS5aZS._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71gfCiUuRWS._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71dk0lH+kgL._AC_SX679_.jpg",
    ],
    description:
      "Apple Macbook Air 2020 Model, (13-Inch, Apple M1 chip with 8-core CPU and 8-core GPU, 8GB, 512GB, MGNE3), Eng-KB, Gold",
    count: 17,
    rating: 4,
    raters: 55,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "14",
    title: "Dell G15-5520 Gaming",
    brand: "Dell",
    category: "laptop",
    price: 1250,
    images: [
      "https://m.media-amazon.com/images/I/419iRv0TWxL._AC_.jpg",
      "https://m.media-amazon.com/images/I/81RxXkllb6L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/811x34QKvRL._AC_SX679_.jpg",
    ],
    description:
      "Dell G15-5520 Gaming Laptop - 12th Intel Core i7-12700H 14-Cores, 16GB RAM DDR5 4800 MHz, 512GB SSD, NVIDIA Geforce RTX3050 4GB GDDR6 Graphics, 15.6 FHD 120 Hz , UBUNTU, Shadow Grey",
    count: 13,
    rating: 4,
    raters: 36,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "15",
    title: "ASUS Vivobook Pro 15",
    brand: "ASUS",
    category: "laptop",
    price: 1300,
    images: [
      "https://m.media-amazon.com/images/I/51WsbKImsEL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/31CTfYOhT3L._AC_SX679_.jpg",
    ],
    description:
      "ASUS Vivobook Pro 15 K3500PC-OLED007W i7-11370H-16GB-SSD 1TB-RTX3050-4GB-15.6 FHD OLED-Windows11-Quiet Blue",
    count: 23,
    rating: 3,
    raters: 24,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "16",
    title: "Forev FV-Q3055",
    brand: "Forev",
    category: "keyboard",
    price: 15,
    images: [
      "https://m.media-amazon.com/images/I/512jZU1nAoS._AC_.jpg",
      "https://m.media-amazon.com/images/I/619zdQE+B-S._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41-kgPhCrZS._AC_.jpg",
    ],
    description: "Forev FV-Q3055 USB Backlighted",
    count: 13,
    rating: 2,
    raters: 21,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "17",
    title: "Logitech G213 Prodigy",
    brand: "Logitech",
    category: "keyboard",
    price: 80,
    images: [
      "https://m.media-amazon.com/images/I/61Nt8geXzWL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61NIjLGSF1L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61dAFDD05RL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/614aoFbb-qL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71jYEvCzciL._AC_SX679_.jpg",
    ],
    description: "Logitech G213 Prodigy RGB Gaming Keyboard - Black",
    count: 8,
    rating: 5,
    raters: 64,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "18",
    title: "Logitech K400 Plus",
    brand: "Logitech",
    category: "keyboard",
    price: 100,
    images: [
      "https://m.media-amazon.com/images/I/71-vSpxZvYL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71GwjmKME8L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81qTdplOdAL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/917BtKFhy-L._AC_SX679_.jpg",
    ],
    description:
      "Logitech K400 Plus Wireless Touch English Keyboard - Dark Grey",
    count: 5,
    rating: 4,
    raters: 45,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "19",
    title: "Logitech G512",
    brand: "Logitech",
    category: "keyboard",
    price: 110,
    images: [
      "https://m.media-amazon.com/images/I/51di6xqLffL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61RbfsMfV0L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61I138tgxGL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61Z3+NNLEyL._AC_SX679_.jpg",
    ],
    description: "Logitech G512 Carbon RGB Mechanical Gaming Keyboard",
    count: 26,
    rating: 4,
    raters: 84,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "20",
    title: "Techno Zone E22",
    brand: "Techno",
    category: "keyboard",
    price: 30,
    images: [
      "https://m.media-amazon.com/images/I/41OiFSiAg-S._AC_.jpg",
      "https://m.media-amazon.com/images/I/41iv+jYXqDS._AC_.jpg",
      "https://m.media-amazon.com/images/I/41wrveuU2wS._AC_.jpg",
    ],
    description: "Techno Zone E22 RGB Mechanical USB Gaming Keyboard (61 Key)",
    count: 9,
    rating: 3,
    raters: 12,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "21",
    title: "Meetion K9520",
    brand: "Meetion",
    category: "keyboard",
    price: 25,
    images: [
      "https://m.media-amazon.com/images/I/51hVxU1Lq0S._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51XM+u7pF6S._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51pwH3B6cFS._AC_SX679_.jpg",
    ],
    description:
      "Meetion K9520 - RGB Magnetic Wrist Rest Gaming Keyboard - Black",
    count: 10,
    rating: 4,
    raters: 62,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "22",
    title: "Redragon K552",
    brand: "Redragon",
    category: "keyboard",
    price: 65,
    images: [
      "https://m.media-amazon.com/images/I/61xRXKoKyKL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61ENOSL5ZsL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71mCKsD7VNL._AC_SX679_.jpg",
    ],
    description:
      "Redragon K552 60% Mechanical Gaming Keyboard RGB Backlit Wired with Red Switches for Windows Gaming PC, UK QWERTY (White)",
    count: 29,
    rating: 5,
    raters: 47,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "23",
    title: "Havit MS1010 Ergonomico",
    brand: "HAVIT",
    category: "mouse",
    price: 13,
    images: [
      "https://m.media-amazon.com/images/I/31WfdwLOk4L._AC_.jpg",
      "https://sc02.alicdn.com/kf/H522788af1c3947c9bfef206255e5b09er/200167142/H522788af1c3947c9bfef206255e5b09er.jpg",
      "https://www.tamata.com/media/catalog/product/cache/b1b762920b4f64fe70902904558ecc11/a/j/ajeadalsad5-2-2021-z-16-2.jpg",
    ],
    description:
      "Havit MS1010 Ergonomico Gamer Raton De Juego Backlit Wired Rgb Gaming Mouse black",
    count: 34,
    rating: 4,
    raters: 37,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "24",
    title: "HAVIT GAMENOTE MS1027",
    brand: "HAVIT",
    category: "mouse",
    price: 9,
    images: [
      "https://m.media-amazon.com/images/I/41RDLIdQctL._AC_.jpg",
      "https://m.media-amazon.com/images/I/51i0V8Sy7pL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41i9PidtP6L._AC_.jpg",
      "https://m.media-amazon.com/images/I/41yFM7B5QEL._AC_.jpg",
    ],
    description:
      "HAVIT GAMENOTE MS1027 Rainbow LED Gaming Mouse - 6 Buttons, 2400 dpi - 2725605868814",
    count: 17,
    rating: 5,
    raters: 54,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "25",
    title: "Logitech Corded",
    brand: "Logitech",
    category: "mouse",
    price: 8,
    images: [
      "https://m.media-amazon.com/images/I/41cXXsd2vBL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41Q96CLGGXL._AC_SY879_.jpg",
      "https://m.media-amazon.com/images/I/61JGO0peSsL._AC_SX679_.jpg",
    ],
    description: "Logitech® Corded Mouse B100 - Business - USB - BLACK",
    count: 6,
    rating: 4,
    raters: 25,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "26",
    title: "Microsoft Wireless Mobile",
    brand: "Microsoft",
    category: "mouse",
    price: 20,
    images: [
      "https://m.media-amazon.com/images/I/61TZs1VORlL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/616+v+O5WuL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/618sR5OWrWL._AC_SX679_.jpg",
    ],
    description: "Microsoft Wireless Mobile Mouse 1850, Black [U7Z-00004]",
    count: 14,
    rating: 5,
    raters: 22,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "27",
    title: "ONIKUMA CW905 RGB",
    brand: "ONIKUMA",
    category: "mouse",
    price: 12,
    images: [
      "https://m.media-amazon.com/images/I/41DVyou2OTL._AC_.jpg",
      "https://www.elitetechjo.com/wp-content/uploads/1634/45/EE00188-0-500x500.jpg.webp",
      "https://iceytech.com/cms/wp-content/uploads/2021/10/CW-905-WIRELESS-black.jpg",
    ],
    description:
      "ONIKUMA CW905 RGB Gaming Mouse – 6400 DPI – 7 Programable Buttons",
    count: 16,
    rating: 3,
    raters: 20,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "28",
    title: "Redragon M711 Cobra",
    brand: "Redragon",
    category: "mouse",
    price: 30,
    images: [
      "https://elbadrgroupeg.store/image/cache/catalog/61iQL1tpmnL._SL1500_-1500x1500.jpg",
      "https://m.media-amazon.com/images/I/71sjT9o51iL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61zb5vsih6L._AC_SX679_.jpg",
    ],
    description: "Redragon M711 Cobra RGB Optical Gaming Mouse",
    count: 7,
    rating: 4,
    raters: 54,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "29",
    title: "Redragon M606 MAMBA",
    brand: "Redragon",
    category: "mouse",
    price: 16,
    images: [
      "https://m.media-amazon.com/images/I/61xWw6dLGJL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/613INe3Di0L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61mjmBLFnOL._AC_SX679_.jpg",
    ],
    description:
      "Redragon M606 MAMBA 7200 DPI 6 Button Programmable Gaming Mouse",
    count: 12,
    rating: 5,
    raters: 31,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "30",
    title: "Fantech X9 THOR",
    brand: "Fantech",
    category: "mouse",
    price: 10,
    images: [
      "https://images-eu.ssl-images-amazon.com/images/I/31QtZp9lzIL._AC_UL210_SR210,210_.jpg",
      "https://m.media-amazon.com/images/I/61zBn2428zL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/619KnAWyauL._AC_SX679_.jpg",
    ],
    description:
      "Fantech Programmable USB Gaming Mouse For PC - X9 THOR Chroma Black",
    count: 16,
    rating: 3,
    raters: 12,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "31",
    title: "M160 HP",
    brand: "Unknown",
    category: "mouse",
    price: 7,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3Vg0hKZlNxKyBnETv4wRF2QqNg1Hx6HKYJFPYVTbNCRFG4V5rJUBuYEhGCZg12xl8CO4&usqp=CAU",
      "https://m.media-amazon.com/images/I/41Q4gE3vHKS._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41O1j65plSS._AC_SX679_.jpg",
    ],
    description: "M160 HP WIRED MOUSE - BLACK",
    count: 7,
    rating: 2,
    raters: 6,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "32",
    title: "HAVIT GAMENOTE H656d",
    brand: "HAVIT",
    category: "headphone",
    price: 20,
    images: [
      "https://m.media-amazon.com/images/I/61zz8HcHykS._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61o0MQEhpxS._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61hnopQ3BwS._AC_SX679_.jpg",
    ],
    description:
      "HAVIT GAMENOTE H656d E-SPORTS Chroma RGB GAMING Headphone 50MM Driver for PC PS4 PS5 / Mobile",
    count: 5,
    rating: 4,
    raters: 15,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "33",
    title: "TGUS Wireless Gaming",
    brand: "TGUS",
    category: "headphone",
    price: 16,
    images: [
      "https://img.joomcdn.net/60ac312123552c84cc0b7de3c5011f79d8ec6872_original.jpeg",
      "https://m.media-amazon.com/images/I/515Vw+IbhWL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51hHa5mW8jL._AC_SX679_.jpg",
    ],
    description:
      "TGUS Wireless Gaming Headset, LED Light Up Cat Ear Shaped Headphones, Cartoon Luminous Head-mounted Stereo Bluetooth Headset, for Kids Adult(Pink)",
    count: 9,
    rating: 3,
    raters: 19,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "34",
    title: "INSMART PC Gaming",
    brand: "INSMART",
    category: "headphone",
    price: 18,
    images: [
      "https://m.media-amazon.com/images/I/61mRLNbiONL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71UMJKF+sZL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71gW5J9ynJL._AC_SX679_.jpg",
    ],
    description:
      "PS5 PS4 Headset, INSMART PC Gaming Headset Over-Ear Gaming Headphones with Mic LED Light Noise Cancelling & Volume Control New Xbox One PS4 PS5 (3.5mm Splitter Cable Included)",
    count: 12,
    rating: 4,
    raters: 18,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "35",
    title: "KOTION EACH G7000",
    brand: "KOTION",
    category: "headphone",
    price: 11,
    images: [
      "https://m.media-amazon.com/images/I/61X2AG6zoyL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61TQaJTclcL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61YRO-TpEUL._AC_SX679_.jpg",
    ],
    description:
      "KOTION EACH G7000 7.1 USB Surround Vibration -HighEnd- Professional Gaming Headset PC Headphone Computer Headband with Mic LED for Gamer",
    count: 8,
    rating: 5,
    raters: 17,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "36",
    title: "Redragon H112",
    brand: "Redragon",
    category: "headphone",
    price: 25,
    images: [
      "https://m.media-amazon.com/images/I/51esnW6sHjS._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51gjR4gpbHS._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51AEANu8MOS._AC_SX679_.jpg",
    ],
    description:
      "Redragon H112 Gaming Headset Crystal Clear Sound And Noise isolation",
    count: 5,
    rating: 4,
    raters: 61,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "37",
    title: "Redragon H320",
    brand: "Redragon",
    category: "headphone",
    price: 50,
    images: [
      "https://m.media-amazon.com/images/I/51D7NaE524L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/5139Tn2KGeL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61rbkTnKH7L._AC_SX679_.jpg",
    ],
    description:
      "Redragon H320 RGB LAMIA2 USB Gaming Headset - Surround Sound 7.1 - Noise Cancelation Microphone With Headset Stand",
    count: 21,
    rating: 5,
    raters: 26,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "38",
    title: "Redragon H350",
    brand: "Redragon",
    category: "headphone",
    price: 56,
    images: [
      "https://m.media-amazon.com/images/I/41mcX2Le2ML._AC_.jpg",
      "https://m.media-amazon.com/images/I/41bjqP+rPAL._AC_.jpg",
      "https://m.media-amazon.com/images/I/51vMSOUgNzL._AC_.jpg",
    ],
    description:
      "Redragon H350 Pandora RGB USB Gaming Headset - 7.1 Surround Sound - 50mm Drivers - Detachable Microphone (Black)",
    count: 12,
    rating: 3,
    raters: 32,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "39",
    title: "Luckyu Cat Ear",
    brand: "Luckyu",
    category: "headphone",
    price: 20,
    images: [
      "https://m.media-amazon.com/images/I/61zlpyPOOaL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51z8iR6OTlL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71yDvFT5KaL._AC_SX679_.jpg",
    ],
    description:
      "Wireless Bluetooth Cat Ear Headphones with Mic 7 Colors LED Light Flashing Glowing On-Ear Stereo Headset Compatible with Smartphones PC Tablet",
    count: 14,
    rating: 4,
    raters: 53,
    addedToCart: false,
    favorite: false,
  },
  {
    id: "40",
    title: "ONIKUMA K6 Stereo",
    brand: "ONIKUMA",
    category: "headphone",
    price: 30,
    images: [
      "https://m.media-amazon.com/images/I/61zCWFEzpLS._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71HhwDz3IhL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71yfLscWjIL._AC_SX679_.jpg",
    ],
    description:
      "K6 Gaming Headset with RGB Light ONIKUMA K6 Stereo Gaming Headset for PS4, PC, Xbox One Controller, Noise Cancelling Over Ear Headphones",
    count: 5,
    rating: 4,
    raters: 36,
    addedToCart: false,
    favorite: false,
  },
];
